
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/gracechang/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:206 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The target system is: iOS -  - 
      The host system is: Darwin - 23.4.0 - arm64
